In [1]:
from numpy import *

random.rand(4,4)

array([[0.90309342, 0.59026701, 0.1858696 , 0.71994215],
       [0.75119625, 0.73156479, 0.15739768, 0.81912456],
       [0.85126972, 0.82165727, 0.72465224, 0.20996462],
       [0.64652762, 0.86104234, 0.45182506, 0.72442078]])

In [3]:
randMat=mat(random.rand(4,4))

In [4]:
randMat

matrix([[0.9958846 , 0.16385475, 0.4743524 , 0.19995114],
        [0.28208571, 0.56521013, 0.24669651, 0.94905119],
        [0.40525891, 0.72028209, 0.84557939, 0.82278216],
        [0.24194843, 0.98218045, 0.89362683, 0.13582331]])

In [7]:
randMat.T

matrix([[0.9958846 , 0.28208571, 0.40525891, 0.24194843],
        [0.16385475, 0.56521013, 0.72028209, 0.98218045],
        [0.4743524 , 0.24669651, 0.84557939, 0.89362683],
        [0.19995114, 0.94905119, 0.82278216, 0.13582331]])

In [8]:
randMat*randMat.I

matrix([[ 1.00000000e+00, -5.55111512e-17,  1.11022302e-16,
          6.93889390e-17],
        [ 5.55111512e-17,  1.00000000e+00, -3.33066907e-16,
          1.38777878e-16],
        [ 5.55111512e-17,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 1.47451495e-17,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]])