In [4]:
from modsim import *

In [194]:
UNITS.Quantity.__init__

<slot wrapper '__init__' of 'object' objects>

In [362]:
class _Vector(UNITS.Quantity):
    """Represented as a Pint Quantity with a NumPy array
    
    x, y, z, mag, mag2, and angle are accessible as attributes.
    
    Supports vector operations hat, dot, cross, proj, and comp.
    """
    
    @property
    def x(self):
        """Returns the x component with units."""
        return self[0]

    @property
    def y(self):
        """Returns the y component with units."""
        return self[1]

    @property
    def z(self):
        """Returns the z component with units."""
        return self[2]

    @property
    def mag(self):
        """Returns the magnitude with units."""
        return np.sqrt(np.dot(self, self)) * self.units

    @property
    def mag2(self):
        """Returns the magnitude squared with units."""
        return np.dot(self, self) * self.units

    @property
    def angle(self):
        """Returns the angle between self and the positive x axis."""
        return np.arctan2(self.y, self.x)

    def polar(self):
        """Returns magnitude and angle."""
        return self.mag, self.angle

    def hat(self):
        """Returns the unit vector in the direction of self."""
        """
        """
        return self / self.mag * self.units

    def dot(self, other):
        """Returns the dot product of self and other."""
        """
        """
        return np.dot(self, other) * self.units * other.units

    def cross(self, other):
        """Returns the cross product of self and other."""
        """
        """
        return np.cross(self, other) * self.units * other.units

    def proj(self, other):
        """Returns the projection of self onto other."""
        """
        """
        return np.dot(self, other) * other.hat()

    def comp(self, other):
        """Returns the magnitude of the projection of self onto other."""
        """
        """
        return np.dot(self, other.hat()) * other.units

    def dist(self, other):
        """Euclidean distance from self to other, with units."""
        diff = self - other
        return diff.mag

    def diff_angle(self, other):
        """
        """
        #TODO: see http://www.euclideanspace.com/maths/algebra/vectors/angleBetween/
        raise NotImplementedError()
        
        
def Vector(*args, units=None):
    # if there's only one argument, it should be iterable
    if len(args) == 1:
        args = args[0]
        
        # if it's a series, pull out the values
        if isinstance(args, Series):
            args = args.values
        
    # see if any of the arguments have unit; if so, save the first one
    for elt in args:
        found_units = getattr(elt, 'units', None)
        if found_units:
            break
            
    if found_units:
        # if there are units, remove them
        args = [getattr(elt, 'magnitude', elt) for elt in args]
    
    # if the units keyword is provided, it overrides the units in args
    if units is not None:
        found_units = units
    
    return _Vector(args, found_units)

In [346]:
m = UNITS.m
N = UNITS.newton

In [347]:
a = Vector(3, 4)
a

<Quantity([3 4], 'dimensionless')>

In [348]:
a = Vector(3, 4, units=m)
a

<Quantity([3 4], 'meter')>

In [349]:
a = Vector([3, 4])
a

<Quantity([3 4], 'dimensionless')>

In [350]:
a = Vector(3, 4*m)
a

<Quantity([3 4], 'meter')>

In [351]:
a = Vector([3, 4*m])
a

<Quantity([3 4], 'meter')>

In [352]:
a = Vector(3, 4*m, units=s) * m
a

<Quantity([ 3.  4.], 'meter * second')>

In [353]:
a = Vector(Series([3, 4]))
a

[3 4]


<Quantity([3 4], 'dimensionless')>

In [354]:
a = Vector(3, 4)
a

<Quantity([3 4], 'dimensionless')>

In [355]:
a = Vector([3, 4]) * m
type(a)

__main__._Vector

In [356]:
a

<Quantity([ 3.  4.], 'meter')>

In [357]:
a * m

<Quantity([ 3.  4.], 'meter ** 2')>

In [358]:
a / m

<Quantity([ 3.  4.], 'dimensionless')>

In [359]:
a[0]

<Quantity(3.0, 'meter')>

In [360]:
a.x

<Quantity(3.0, 'meter')>

In [361]:
a.y

<Quantity(4.0, 'meter')>

In [216]:
a.mag

<Quantity(5.0, 'meter')>

In [217]:
a.mag2

<Quantity(25.0, 'meter')>

In [218]:
type(a)

__main__._Vector

In [219]:
type(a.mag)

pint.unit.build_quantity_class.<locals>.Quantity

In [220]:
c = a * a.mag
c

<Quantity([ 15.  20.], 'meter ** 2')>

In [221]:
c = a / a.mag
c

<Quantity([ 0.6  0.8], 'dimensionless')>

In [222]:
c.x

<Quantity(0.6, 'dimensionless')>

In [223]:
ah = a.hat()
ah

<Quantity([ 0.6  0.8], 'meter')>

In [224]:
print(ah)

[ 0.6  0.8] meter


In [225]:
ah.units

<Unit('meter')>

In [226]:
b = Vector([1, 2])

In [227]:
a.dot(b)

<Quantity(11.0, 'meter')>

In [228]:
N = UNITS.newton

b = Vector([1, 2]) * N

In [229]:
a.dot(b)

<Quantity(11.0, 'meter * newton')>

In [230]:
c = a.cross(b)
c

<Quantity(2.0, 'meter * newton')>

In [231]:
c = a.proj(b)

In [232]:
c

<Quantity([ 4.91934955  9.8386991 ], 'newton')>

In [233]:
a.comp(b)

<Quantity(4.919349550499537, 'newton')>

In [234]:
x_hat = Vector([1, 0])
y_hat = Vector([0, 1])

In [235]:
a.comp(x_hat)

<Quantity(3.0, 'dimensionless')>

In [236]:
a.comp(y_hat)

<Quantity(4.0, 'dimensionless')>

In [237]:
a.angle

<Quantity(0.9272952180016122, 'radian')>

In [238]:
b.angle

<Quantity(1.1071487177940904, 'radian')>

In [239]:
Vector([1, 1]).angle / pi

<Quantity(0.25, 'radian')>

In [240]:
Vector([-1, 1]).angle / pi

<Quantity(0.75, 'radian')>

In [241]:
Vector([-1, -1]).angle / pi

<Quantity(-0.75, 'radian')>

In [242]:
Vector([1, -1]).angle / pi

<Quantity(-0.25, 'radian')>

In [243]:
Vector([1, -1]).polar()

(<Quantity(1.4142135623730951, 'dimensionless')>,
 <Quantity(-0.7853981633974483, 'radian')>)

In [244]:
x = [5, 3.5355, 0, -10]
x

[5, 3.5355, 0, -10]

In [245]:
y = [0, 3.5355, 10, 0]
y

[0, 3.5355, 10, 0]

In [246]:
theta, rho = cart2pol(x,y)

In [247]:
theta

array([ 0.        ,  0.78539816,  1.57079633,  3.14159265])

In [248]:
rho

array([  5.        ,   4.99995205,  10.        ,  10.        ])

In [249]:
theta = [0, pi/4, pi/2, pi]

In [250]:
rho = [5, 5, 10, 10]

In [251]:
x2, y2 = pol2cart(theta,rho)

In [252]:
print(x2)

[  5.00000000e+00   3.53553391e+00   6.12323400e-16  -1.00000000e+01]


In [253]:
print(y2)

[  0.00000000e+00   3.53553391e+00   1.00000000e+01   1.22464680e-15]


In [254]:
degree = UNITS.degree
kg = UNITS.kg
m = UNITS.m
s = UNITS.s

In [255]:
condition = Condition(x = 0 * m, 
                      y = 0 * m,
                      g = 9.8 * m/s**2,
                      mass = 145e-3 * kg,
                      diameter = 73e-3 * m,
                      rho = 1.2 * kg/m**3,
                      C_d = 0.3,
                      angle = 45 * degree,
                      velocity = 40 * m / s,
                      duration = 5 * s)

In [256]:
def make_system(condition):
    unpack(condition)
    
    theta = np.deg2rad(angle)
    vx, vy = pol2cart(theta, velocity)
    init = State(x=x, y=y, vx=vx, vy=vy)
    v = State(vx=vx, vy=vy)
    
    area = np.pi * (diameter/2)**2
    ts = linspace(0, duration, 101)
    
    return System(init=init, g=g, mass=mass, v=v,
                  area=area, rho=rho, C_d=C_d, ts=ts)

In [257]:
system = make_system(condition)
system.init

x                               0 meter
y                               0 meter
vx    28.284271247461902 meter / second
vy      28.2842712474619 meter / second
dtype: object

In [258]:
v = system.v.values
v

array([<Quantity(28.284271247461902, 'meter / second')>,
       <Quantity(28.2842712474619, 'meter / second')>], dtype=object)

In [363]:
def slope_func(state, t, system):
    x, y, vx, vy = state
    unpack(system)
    
    a_grav = Vector(0, -g)

    v = Vector(vx, vy)
    
    f_drag = -rho * v.mag * v * C_d * area / 2
    a_drag = f_drag / mass

    a = a_grav + a_drag
    
    return v, a

In [364]:
slope_func(system.init, 0, system)

(<Quantity([ 28.28427125  28.28427125], 'meter / second')>,
 <Quantity([ -5.87820989 -15.67820989], 'meter / second ** 2')>)

In [261]:
a = 5 * m

In [262]:
b = Vector([1, 2]) * s

In [263]:
b * a

<Quantity([  5.  10.], 'meter * second')>

In [264]:
a * b

<Quantity([  5.  10.], 'meter * second')>